# Generated by Django 6.0.5 on 2026-05-14 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountyHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=100)),
                ('established_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegionalSphere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lead_director', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('assigned_hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.countyhub')),
            ],
        ),
        migrations.AddField(
            model_name='countyhub',
            name='sphere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.regionalsphere'),
        ),
    ]
