# Generated by Django 6.0.5 on 2026-05-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardwareinventory',
            old_name='assigned_hub',
            new_name='hub',
        ),
        migrations.RemoveField(
            model_name='countyhub',
            name='established_date',
        ),
        migrations.RemoveField(
            model_name='regionalsphere',
            name='lead_director',
        ),
        migrations.AddField(
            model_name='countyhub',
            name='image',
            field=models.ImageField(default='hub_images/default.jpg', upload_to='hub_images/'),
        ),
        migrations.AlterField(
            model_name='hardwareinventory',
            name='equipment_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hardwareinventory',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regionalsphere',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
