# Generated by Django 6.0.5 on 2026-05-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_assigned_hub_hardwareinventory_hub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('statement', models.TextField()),
                ('image', models.ImageField(default='directors/default.jpg', upload_to='directors/')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
