# Generated by Django 6.0.5 on 2026-05-14 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='hub_documents/')),
                ('category', models.CharField(choices=[('blueprint', 'Technical Blueprint'), ('research', 'Scientific Research'), ('log', 'Field Log'), ('video', 'Project Media')], default='blueprint', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.countyhub')),
            ],
        ),
    ]
