# Generated by Django 6.0.5 on 2026-05-15 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hubdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubdocument',
            name='category',
            field=models.CharField(choices=[('blueprint', 'Technical Blueprint'), ('research', 'Scientific Research'), ('log', 'Field Log')], default='blueprint', max_length=20),
        ),
        migrations.CreateModel(
            name='HubVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='hub_videos/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.countyhub')),
            ],
        ),
    ]
