# Generated by Django 6.0.5 on 2026-05-15 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_hubdocument_category_hubvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubdocument',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hubvideo',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hardwareinventory',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.countyhub'),
        ),
        migrations.AlterField(
            model_name='hardwareinventory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
