# Generated by Django 6.0.5 on 2026-05-15 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hubdocument_is_public_hubvideo_is_public_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardwareinventory',
            options={'verbose_name_plural': 'Hardware Inventories'},
        ),
        migrations.RemoveField(
            model_name='hubdocument',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='hubvideo',
            name='uploaded_at',
        ),
    ]
