# Generated by Django 6.0.5 on 2026-05-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_hardwareinventory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideshowImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Nimba Project Team', max_length=100)),
                ('image', models.ImageField(upload_to='slideshow/')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this image from the slideshow')),
                ('order', models.IntegerField(default=0, help_text='1 shows first, 2 shows second, etc.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
