# Generated by Django 6.0.5 on 2026-05-15 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_slideshowimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to de-activate the code.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='RegionalSphere',
            new_name='Sphere',
        ),
        migrations.RemoveField(
            model_name='hubdocument',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='hubvideo',
            name='hub',
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='director',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slideshowimage',
            name='is_active',
        ),
        migrations.AddField(
            model_name='countyhub',
            name='allocated_funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='countyhub',
            name='description',
            field=models.TextField(blank=True, help_text='Technical summary of the local project.'),
        ),
        migrations.AddField(
            model_name='countyhub',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Enter a number from 0 to 100 for the progress bar.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='countyhub',
            name='project_title',
            field=models.CharField(default='Infrastructure Development', max_length=200),
        ),
        migrations.AddField(
            model_name='countyhub',
            name='status',
            field=models.CharField(choices=[('SR', 'Surveying'), ('GB', 'Groundbreaking'), ('AC', 'Active Construction'), ('CP', 'Completed'), ('HI', 'On Hiatus')], default='SR', max_length=2),
        ),
        migrations.AddField(
            model_name='countyhub',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='countyhub',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo link for project updates.'),
        ),
        migrations.AddField(
            model_name='director',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='directors/'),
        ),
        migrations.AlterField(
            model_name='countyhub',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hub_images/'),
        ),
        migrations.AlterField(
            model_name='director',
            name='order',
            field=models.IntegerField(default=0, help_text='The order in which they appear on the page.'),
        ),
        migrations.AlterField(
            model_name='director',
            name='statement',
            field=models.TextField(help_text="The director's personal or professional mission statement."),
        ),
        migrations.AlterField(
            model_name='slideshowimage',
            name='order',
            field=models.IntegerField(default=0, help_text='Determines the sequence (0, 1, 2, 3).'),
        ),
        migrations.AlterField(
            model_name='slideshowimage',
            name='title',
            field=models.CharField(blank=True, help_text='Internal label for the image.', max_length=100),
        ),
        migrations.DeleteModel(
            name='HardwareInventory',
        ),
        migrations.DeleteModel(
            name='HubDocument',
        ),
        migrations.DeleteModel(
            name='HubVideo',
        ),
    ]
