# Generated by Django 6.0.5 on 2026-05-15 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_accesscode_rename_regionalsphere_sphere_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('planned', 'PROPOSED'), ('active', 'IN PROGRESS'), ('completed', 'DEPLOYED')], default='planned', max_length=20)),
                ('completion_rate', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AccessCode',
        ),
        migrations.AlterModelOptions(
            name='director',
            options={},
        ),
        migrations.AlterModelOptions(
            name='slideshowimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='countyhub',
            name='allocated_funds',
        ),
        migrations.RemoveField(
            model_name='countyhub',
            name='description',
        ),
        migrations.RemoveField(
            model_name='countyhub',
            name='image',
        ),
        migrations.RemoveField(
            model_name='countyhub',
            name='project_title',
        ),
        migrations.RemoveField(
            model_name='countyhub',
            name='total_budget',
        ),
        migrations.RemoveField(
            model_name='countyhub',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='director',
            name='order',
        ),
        migrations.AddField(
            model_name='countyhub',
            name='coordinates',
            field=models.CharField(blank=True, help_text='Lat/Long for telemetry look', max_length=50),
        ),
        migrations.AlterField(
            model_name='countyhub',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='countyhub',
            name='status',
            field=models.CharField(choices=[('inactive', 'OFFLINE / PENDING'), ('active', 'OPERATIONAL'), ('maintenance', 'SYSTEM MAINTENANCE')], default='inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='director',
            name='statement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='director',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='slideshowimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='slideshowimage',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.countyhub'),
        ),
    ]
