# Generated by Django 6.0.5 on 2026-05-15 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_delete_accesscode_alter_director_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countyhub',
            name='progress_percentage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='completion_rate',
        ),
        migrations.AlterField(
            model_name='countyhub',
            name='coordinates',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project')),
            ],
        ),
    ]
